module vtop (
    input  clk_50m_in, reset_l,
    input  sim_gmii_rx_clk, sim_gmii_rx_dv,
    input  [7:0] sim_gmii_rxd,
    output [7:0] sim_gmii_txd,
    output sim_gmii_tx_en,
    output sim_cpu_rd_empty,
    output [3:0] led_o,

    // Debug probes from webserver_cpu_top
    output       dbg_rx_afifo_empty,
    output       dbg_rx_presemble_valid,
    output [9:0] dbg_rx_afifo_data,
    output       dbg_mac_rx_sop,
    output       dbg_mac_rx_en,
    output [7:0] dbg_mac_rx_data,
    output       dbg_mac_rx_eop,
    output       dbg_mac_tx_sop,
    output       dbg_mac_tx_en,
    output [7:0] dbg_mac_tx_data,
    output       dbg_mac_tx_eop,
    output       dbg_bus_req,
    output       dbg_bus_rhwl,
    output [31:0] dbg_bus_address,
    output [31:0] dbg_bus_wdata,
    output [31:0] dbg_bus_rdata,
    // CPU debug (PicoRV32 state)
    output       dbg_cpu_trap,
    output       dbg_cpu_valid,
    output [31:0] dbg_cpu_addr,
    output [12:0] dbg_mac_in_wpkt_len,
    output       dbg_mac_in_wpkt_push,
    output       dbg_para_wen,
    output [12:0] dbg_para_len,
    output       dbg_para_full_reg,
    output       dbg_rpkt_pop,
    output [12:0] dbg_rpkt_para_len,
    output [12:0] dbg_rpkt_para_data_r_len,

    // ILA register bus
    input        ila_reg_we,
    input [15:0] ila_reg_addr,
    input [31:0] ila_reg_wdata,
    output [31:0] ila_reg_rdata
);
    webserver_cpu_top #(.sim_mod(1)) u_dut (
        .clk_50m_in, .reset_l,
        .rgmii_rxc(0), .rgmii_rxd(0), .rgmii_rx_ctl(0),
        .rgmii_txc(), .rgmii_txd(), .rgmii_tx_ctl(),
        .Eth0_MDC(), .Eth0_MDIO(), .rgmii_reset_l(),
        .uart_rx(1), .uart_tx(),
        .led_o,
        .sim_gmii_rx_clk, .sim_gmii_rxd, .sim_gmii_rx_dv,
        .sim_gmii_txd, .sim_gmii_tx_en,
        .sim_cpu_rd_empty, .sim_gmii_rx_dv_out(),
        .dbg_mac_rx_sop(dbg_mac_rx_sop), .dbg_mac_rx_en(dbg_mac_rx_en),
        .dbg_mac_rx_data(dbg_mac_rx_data), .dbg_mac_rx_eop(dbg_mac_rx_eop),
        .dbg_rx_afifo_empty(dbg_rx_afifo_empty),
        .dbg_rx_presemble_valid(dbg_rx_presemble_valid),
        .dbg_rx_afifo_data(dbg_rx_afifo_data),
        .dbg_mac_tx_sop(dbg_mac_tx_sop),
        .dbg_mac_tx_en(dbg_mac_tx_en),
        .dbg_mac_tx_data(dbg_mac_tx_data),
        .dbg_mac_tx_eop(dbg_mac_tx_eop),
        .dbg_bus_req(dbg_bus_req),
        .dbg_bus_rhwl(dbg_bus_rhwl),
        .dbg_bus_address(dbg_bus_address),
        .dbg_bus_wdata(dbg_bus_wdata),
        .dbg_bus_rdata(dbg_bus_rdata),
        .dbg_cpu_trap(dbg_cpu_trap),
        .dbg_cpu_valid(dbg_cpu_valid),
        .dbg_cpu_addr(dbg_cpu_addr),
        .dbg_mac_in_wpkt_len(dbg_mac_in_wpkt_len),
        .dbg_mac_in_wpkt_push(dbg_mac_in_wpkt_push),
        .dbg_para_wen(dbg_para_wen),
        .dbg_para_len(dbg_para_len),
        .dbg_para_full_reg(dbg_para_full_reg),
        .dbg_rpkt_pop(dbg_rpkt_pop),
        .dbg_rpkt_para_len(dbg_rpkt_para_len),
        .dbg_rpkt_para_data_r_len(dbg_rpkt_para_data_r_len)
    );

    ila_wrapper u_ila (
        .clk(clk_50m_in), .reset_l(reset_l),
        .gmii_rx_dv(sim_gmii_rx_dv), .gmii_rxd(sim_gmii_rxd),
        .gmii_tx_en(sim_gmii_tx_en), .gmii_txd(sim_gmii_txd),
        .cpu_rd_empty(sim_cpu_rd_empty), .led_o(led_o),
        .rx_afifo_empty(dbg_rx_afifo_empty),
        .rx_presemble_valid(dbg_rx_presemble_valid),
        .mac_tx_sop(dbg_mac_tx_sop), .mac_tx_en(dbg_mac_tx_en),
        .mac_tx_data(dbg_mac_tx_data), .mac_tx_eop(dbg_mac_tx_eop),
        .bus_req(dbg_bus_req), .bus_addr_lo(dbg_bus_address[11:0]),
        .bus_rhwl(dbg_bus_rhwl),
        .reg_we(ila_reg_we), .reg_addr(ila_reg_addr),
        .reg_wdata(ila_reg_wdata), .reg_rdata(ila_reg_rdata)
    );
endmodule
